from astralengine.ecs.world import ECSWorld
from astralengine.input.frame import system_input_begin_frame
from astralengine.systems.player.player_controller_system import system_player_controller
from astralengine.systems.camera.camera_matrices_system import system_update_camera_matrices
from astralengine.systems.camera.parent_follow_system import system_parent_follow
from astralengine.systems.physics.gravity_system import system_gravity
from astralengine.systems.physics.movement_system import system_movement
from astralengine.systems.render.update_model_matrices_system import system_update_model_matrices
from astralengine.voxels.systems.chunk_remesh_system import system_chunk_remesh
from astralengine.renderer.submit.submit_chunk_system import system_submit_chunks
from astralengine.renderer.submit.submit_camera_system import system_submit_camera
from astralengine.renderer.submit.submit_debug_system import system_submit_debug
from astralengine.renderer.submit.submit_skybox_system import system_submit_skybox
from astralengine.renderer.renderer import system_execute_render_pipeline


def install_core_systems(world: ECSWorld) -> None:
    pass
