from __future__ import annotations

from typing import Iterator


ChunkKey = tuple[int, int, int, int]


class ChunkStreamIndex:
    def __init__(self) -> None: ...
    def bind(self, frame_eid: int, coord: tuple[int, int, int], eid: int) -> None: ...
    def unbind(self, frame_eid: int, coord: tuple[int, int, int]) -> int | None: ...
    def get(self, frame_eid: int, coord: tuple[int, int, int]) -> int | None: ...
    def has(self, frame_eid: int, coord: tuple[int, int, int]) -> bool: ...
    def iter_frame(self, frame_eid: int) -> Iterator[tuple[tuple[int, int, int], int]]: ...