from __future__ import annotations


def voxels_per_meter(voxel_size_m: float) -> float: ...
def meters_to_voxels(distance_m: float, voxel_size_m: float) -> int: ...
def voxels_to_meters(count: int, voxel_size_m: float) -> float: ...