from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Iterator


@dataclass(slots=True)
class FrameNode:
    frame_eid: int
    parent_frame_eid: int


class FrameGraph:
    def __init__(self) -> None: ...
    def bind(self, frame_eid: int, parent_frame_eid: int) -> None: ...
    def unbind(self, frame_eid: int) -> None: ...
    def parent_of(self, frame_eid: int) -> int | None: ...
    def children_of(self, frame_eid: int) -> int | None: ...
    def has_frame(self, frame_eid: int) -> bool: ...
    def iter_roots(self) -> Iterator[int]: ...
    def iter_chain_to_root(self, frame_eid: int) -> Iterator[int]: ...
    def would_create_cycle(self, frame_eid: int, parent_frame_eid: int) -> bool: ...
    def clear(self) -> None: ...